// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL_StcbsqOawNzr7KSZ0Z0pWmEJ5CC7BU',
    appId: '1:1008134080294:web:f92639635893686e7fa3e7',
    messagingSenderId: '1008134080294',
    projectId: 'arrive-b3b7a',
    authDomain: 'arrive-b3b7a.firebaseapp.com',
    storageBucket: 'arrive-b3b7a.appspot.com',
    measurementId: 'G-DQX2KNPJC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5btmBP6hslrMKmfQcfXsTz1zdKrqsZps',
    appId: '1:1008134080294:android:428de16161019e4f7fa3e7',
    messagingSenderId: '1008134080294',
    projectId: 'arrive-b3b7a',
    storageBucket: 'arrive-b3b7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqS1qdIMHEkUROCv2PghORm-4ZYzxy8D0',
    appId: '1:1008134080294:ios:063c7845d23d262a7fa3e7',
    messagingSenderId: '1008134080294',
    projectId: 'arrive-b3b7a',
    storageBucket: 'arrive-b3b7a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqS1qdIMHEkUROCv2PghORm-4ZYzxy8D0',
    appId: '1:1008134080294:ios:063c7845d23d262a7fa3e7',
    messagingSenderId: '1008134080294',
    projectId: 'arrive-b3b7a',
    storageBucket: 'arrive-b3b7a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL_StcbsqOawNzr7KSZ0Z0pWmEJ5CC7BU',
    appId: '1:1008134080294:web:5dfc92b0985bfae87fa3e7',
    messagingSenderId: '1008134080294',
    projectId: 'arrive-b3b7a',
    authDomain: 'arrive-b3b7a.firebaseapp.com',
    storageBucket: 'arrive-b3b7a.appspot.com',
    measurementId: 'G-L8X7F45EXM',
  );

}